import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Image from "next/image";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-white flex-col h-screen`}
      >
        <nav className="justify-between bg-accent py-3 flex items-center">
          <span className="flex space-x-2 items-center px-6">
            <Image
              src="/logoChat.png"
              alt="Hero image"
              width={48}
              height={48}
            />
            <label htmlFor="" className="text-white">
              Zimbo Chat
            </label>
          </span>
          <div className="space-x-6 flex px-6">
            <span className="bg-white text-black rounded-full p-2">
              anesu nyakonda
            </span>
            <button className="text-white">Log Out</button>
          </div>
        </nav>
        {children}
      </body>
    </html>
  );
}
