import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Providers } from "./provider";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="dark">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-main flex h-screen w-full  `}
      >
        <Providers>{children}</Providers>
        <footer>
          <hr className="md:mx-28 mt-10 border-zinc-800" />
          <div className="flex justify-between mt-10">
            <p className="font-light text-xs md:mx-28">
              &copy;{new Date().getFullYear()} Anesu Nyakonda
            </p>
            <div className="flex space-x-5">
              <p className="font-light text-xs   underline">
                Terms & conditions
              </p>
              <p className="font-light text-xs underline pr-10">
                Privacy Policy
              </p>
            </div>
          </div>
        </footer>
      </body>
    </html>
  );
}
